### PR TITLE
expiration date fix

### LINKED ISSUE #130: Expiration Date mismatch on 0.13
- ObjectivePGP version: 0.13.0
- Platform (iOS/macOS): Both

# Description

Expiration dates don't match between GPGTools & ObjectivePGP.

# Steps to reproduce

Example:

[Different Expiration Date.asc.zip](https://github.com/krzyzanowskim/ObjectivePGP/files/2871653/Different.Expiration.Date.asc.zip)

screen shot 2019-02-16 at 11 37 05 am

From ObjectivePGP:

screen shot 2019-02-16 at 11 40 25 am

I've also noticed that in `primaryUserAndSelfCertificate:`:

```
- (nullable PGPUser *)primaryUserAndSelfCertificate:(PGPSignaturePacket *__autoreleasing _Nullable *)selfCertificateOut {
    PGPUser *foundUser = nil;

    for (PGPUser *user in self.users) {
        if (!user.userID || user.userID.length == 0) {
            continue;
        }

        let selfCertificate = user.latestSelfCertificate;
        if (!selfCertificate) {
            continue;
        }

        if (selfCertificate.isPrimaryUserID) {
            foundUser = user;      <====== user and certificate don't match
        } else if (!foundUser) {
            foundUser = user;       <====== user and certificate don't match
        }

        if (selfCertificateOut) {
            *selfCertificateOut = selfCertificate;      <====== user and certificate don't match
        }
    }
    return foundUser;
}
```

So it will take the first user, and last certificate. Changing the certificate to match the user returns a date in 2021. So still not the same.

### PR DESCRIPTION
**Pull request by krzyzanowskim**
Fixes #130 

Changes proposed in this pull request:
- Fixes expiration date calculations
- Distinct signature and key expiration dates
- Improved primary user selection

### CODE REVIEW

File: ObjectivePGP/Packets/PGPSignaturePacket.m [hunk 1]
```diff
@@ -140,15 +140,16 @@ - (nullable PGPKeyID *)issuerKeyID {
...
+// Note: this is not a key expiration date.
 - (nullable NSDate *)expirationDate {
-    let creationDateSubpacket = PGPCast([self subpacketsOfType:PGPSignatureSubpacketTypeSignatureCreationTime].firstObject, PGPSignatureSubpacket);
-    var validityPeriodSubpacket = PGPCast([self subpacketsOfType:PGPSignatureSubpacketTypeSignatureExpirationTime].firstObject, PGPSignatureSubpacket);
-    if (!validityPeriodSubpacket) {
-        validityPeriodSubpacket = PGPCast([self subpacketsOfType:PGPSignatureSubpacketTypeKeyExpirationTime].firstObject, PGPSignatureSubpacket);
+    let _Nullable creationDate = self.creationDate;
+    if (!creationDate) {
+        return nil;
     }
```
Comment (krzyzanowskim) [inline ObjectivePGP/Packets/PGPSignaturePacket.m]: this mitigated the real issue
